(function(){function f(a){"string"!==typeof a&&(a=String(a));if(/[^a-z0-9\-#$%&'*+.\^_`|~]/i.test(a))throw new TypeError("Invalid character in header field name");return a.toLowerCase()}function r(a){"string"!==typeof a&&(a=String(a));return a}function e(a){this.map={};a instanceof e?a.forEach(function(a,c){this.append(c,a)},this):a&&Object.getOwnPropertyNames(a).forEach(function(b){this.append(b,a[b])},this)}function q(a){if(a.bodyUsed)return Promise.reject(new TypeError("Already read"));a.bodyUsed=
!0}function t(a){return new Promise(function(b,c){a.onload=function(){b(a.result)};a.onerror=function(){c(a.error)}})}function v(a){var b=new FileReader;b.readAsArrayBuffer(a);return t(b)}function u(){this.bodyUsed=!1;this._initBody=function(a,b){this._bodyInit=a;if("string"===typeof a)this._bodyText=a;else if(l.blob&&Blob.prototype.isPrototypeOf(a))this._bodyBlob=a,this._options=b;else if(l.formData&&FormData.prototype.isPrototypeOf(a))this._bodyFormData=a;else if(!a)this._bodyText="";else if(!l.arrayBuffer||
!ArrayBuffer.prototype.isPrototypeOf(a))throw Error("unsupported BodyInit type");};l.blob?(this.blob=function(){var a=q(this);if(a)return a;if(this._bodyBlob)return Promise.resolve(this._bodyBlob);if(this._bodyFormData)throw Error("could not read FormData body as blob");return Promise.resolve(new Blob([this._bodyText]))},this.arrayBuffer=function(){return this.blob().then(v)},this.text=function(){var a=q(this);if(a)return a;if(this._bodyBlob){var b=this._bodyBlob,c=this._options,a=new FileReader,
c=c.headers.map["content-type"]?c.headers.map["content-type"].toString():"",n=/charset\=[0-9a-zA-Z\-\_]*;?/,c=b.type.match(n)||c.match(n),b=[b];c&&b.push(c[0].replace(/^charset\=/,"").replace(/;$/,""));a.readAsText.apply(a,b);return t(a)}if(this._bodyFormData)throw Error("could not read FormData body as text");return Promise.resolve(this._bodyText)}):this.text=function(){var a=q(this);return a?a:Promise.resolve(this._bodyText)};l.formData&&(this.formData=function(){return this.text().then(w)});this.json=
function(){return this.text().then(JSON.parse)};return this}function g(a,b){b=b||{};var c=b.body;if(g.prototype.isPrototypeOf(a)){if(a.bodyUsed)throw new TypeError("Already read");this.url=a.url;this.credentials=a.credentials;b.headers||(this.headers=new e(a.headers));this.method=a.method;this.mode=a.mode;c||(c=a._bodyInit,a.bodyUsed=!0)}else this.url=a;this.credentials=b.credentials||this.credentials||"omit";if(b.headers||!this.headers)this.headers=new e(b.headers);a=b.method||this.method||"GET";
var n=a.toUpperCase();this.method=-1<x.indexOf(n)?n:a;this.mode=b.mode||this.mode||null;this.referrer=null;if(("GET"===this.method||"HEAD"===this.method)&&c)throw new TypeError("Body not allowed for GET or HEAD requests");this._initBody(c,b)}function w(a){var b=new FormData;a.trim().split("&").forEach(function(a){if(a){var c=a.split("=");a=c.shift().replace(/\+/g," ");c=c.join("=").replace(/\+/g," ");b.append(decodeURIComponent(a),decodeURIComponent(c))}});return b}function y(a){var b=new e;a.getAllResponseHeaders().trim().split("\n").forEach(function(a){var c=
a.trim().split(":");a=c.shift().trim();c=c.join(":").trim();b.append(a,c)});return b}function h(a,b){b||(b={});this._initBody(a,b);this.type="default";this.status=b.status;this.ok=200<=this.status&&300>this.status;this.statusText=b.statusText;this.headers=b.headers instanceof e?b.headers:new e(b.headers);this.url=b.url||""}if(self.__disableNativeFetch||!self.fetch){e.prototype.append=function(a,b){a=f(a);b=r(b);var c=this.map[a];c||(c=[],this.map[a]=c);c.push(b)};e.prototype["delete"]=function(a){delete this.map[f(a)]};
e.prototype.get=function(a){return(a=this.map[f(a)])?a[0]:null};e.prototype.getAll=function(a){return this.map[f(a)]||[]};e.prototype.has=function(a){return this.map.hasOwnProperty(f(a))};e.prototype.set=function(a,b){this.map[f(a)]=[r(b)]};e.prototype.forEach=function(a,b){Object.getOwnPropertyNames(this.map).forEach(function(c){this.map[c].forEach(function(e){a.call(b,e,c,this)},this)},this)};var p;if(p="FileReader"in self&&"Blob"in self)try{new Blob,p=!0}catch(a){p=!1}var l={blob:p,formData:"FormData"in
self,arrayBuffer:"ArrayBuffer"in self},x="DELETE GET HEAD OPTIONS POST PUT".split(" ");g.prototype.clone=function(){return new g(this)};u.call(g.prototype);u.call(h.prototype);h.prototype.clone=function(){return new h(this._bodyInit,{status:this.status,statusText:this.statusText,headers:new e(this.headers),url:this.url})};h.error=function(){var a=new h(null,{status:0,statusText:""});a.type="error";return a};var z=[301,302,303,307,308];h.redirect=function(a,b){if(-1===z.indexOf(b))throw new RangeError("Invalid status code");
return new h(null,{status:b,headers:{location:a}})};self.Headers=e;self.Request=g;self.Response=h;self.fetch=function(a,b){return new Promise(function(c,e){function f(){if(4===d.readyState){var a=1223===d.status?204:d.status;if(100>a||599<a)m||(m=!0,e(new TypeError("Network request failed")));else{var b=d.statusText,f=y(d),g;g="responseURL"in d?d.responseURL:/^X-Request-URL:/m.test(d.getAllResponseHeaders())?d.getResponseHeader("X-Request-URL"):void 0;a={status:a,statusText:b,headers:f,url:g};b="response"in
d?d.response:d.responseText;m||(m=!0,c(new h(b,a)))}}}var k;k=g.prototype.isPrototypeOf(a)&&!b?a:new g(a,b);var d=new XMLHttpRequest,m=!1;d.onreadystatechange=f;d.onload=f;d.onerror=function(){m||(m=!0,e(new TypeError("Network request failed")))};d.open(k.method,k.url,!0);try{"include"===k.credentials&&("withCredentials"in d?d.withCredentials=!0:console&&console.warn&&console.warn("withCredentials is not supported, you can ignore this warning"))}catch(A){console&&console.warn&&console.warn("set withCredentials error:"+
A)}"responseType"in d&&l.blob&&(d.responseType="blob");k.headers.forEach(function(a,b){d.setRequestHeader(b,a)});d.send("undefined"===typeof k._bodyInit?null:k._bodyInit)})};self.fetch.polyfill=!0;"undefined"!==typeof module&&module.exports&&(module.exports=self.fetch)}})();
